URL="https://www.saucedemo.com/"
dataPath = "data/invalid_login.xlsx"
username = "user-name"
password = "password"
loginButton = "login-button"
tupleUsrPwd = "username,password"
incorrectLoginMsg = "Epic sadface: Username and password do not match any user in this service"